const mongoose=require('mongoose')
const Schema=mongoose.Schema

const userSchema=new Schema({
    Number:{
        required:true,
        type:String
    },
    DeviceId:{
        required:true,
        type:String
    },
    Uns_attempt:{
        required:true,
        type:Number
    },
    is_ban:{
        required:true,
        type:Boolean
    },
    EmailAddress:{
        required:true,
        type:String
    },
    Added_Email:{
        required:true,
        type:Boolean
    },
    Email_Activator_code:{
        required:true,
        type:String
    },
    HashingPassword:{
        required:true,
        type:String
    },
    change_Number_code:{
        required:true,
        type:String
    },
    change_Device_code:{
        required:true,
        type:String
    },
    change_Device_Time:{
        required:true,
        type:Number
    },
    recoverycode:{
        required:true,
        type:String
    },
    Del_Acc_Link:{
        required:true,
        type:String
    },
    loginCode:{
        required:true,
        type:String
    },
    AutoLogin:{
        loginCode:{
            required:true,
            type:String
        },
        Address:{
            required:true,
            type:String
        },
        ExpTime:{
            required:true,
            type:Number
        }
    },
    sites:[{
        SiteAddress:{
            type:String
        },
        username:{
            type:String
        },
        HashingCode:{
            type:String
        },
        expireTime:{
            type:Number
        },
        is_expired:{
            type:Boolean
        }
    }]
})

module.exports=mongoose.model('User',userSchema)
